# Generated by Django 3.2.5 on 2022-02-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(default=5690, primary_key=True, serialize=False),
        ),
    ]
