# Generated by Django 3.2.5 on 2022-02-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Main', 'Main'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], default='Main', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(default=9333, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('IN', 'In Stock'), ('OUT', 'Out of Stock')], default='IN', max_length=3),
        ),
    ]
