# Generated by Django 3.2.5 on 2022-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_auto_20220220_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(default=5970, primary_key=True, serialize=False),
        ),
    ]
