# Generated by Django 3.2.5 on 2022-02-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0019_auto_20220221_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.CharField(default='M3820', max_length=5, primary_key=True, serialize=False),
        ),
    ]
