# Generated by Django 3.2.5 on 2022-02-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0020_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(default=7624, primary_key=True, serialize=False),
        ),
    ]
