# Generated by Django 3.2.5 on 2022-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_auto_20220220_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.IntegerField(default=6615, editable=False, primary_key=True, serialize=False),
        ),
    ]
