# Generated by Django 3.2.5 on 2022-02-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0007_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.IntegerField(default=9058, editable=False, primary_key=True, serialize=False),
        ),
    ]
