# Generated by Django 3.2.5 on 2022-02-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0010_auto_20220220_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
