# Generated by Django 3.2.5 on 2022-02-21 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0013_auto_20220221_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 20, 59, 8, 764364)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 20, 59, 8, 764364)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.CharField(default='R9657', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
