# Generated by Django 3.2.5 on 2022-02-21 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0014_auto_20220221_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 21, 16, 44, 116960)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 21, 16, 44, 116960)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.CharField(default='R4551', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
