# Generated by Django 3.2.5 on 2022-02-21 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0016_auto_20220221_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 21, 33, 43, 665412)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 21, 33, 43, 665412)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.CharField(default='R3457', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
